version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --aot
      - MAIN_JS_FILE=$(find dist/coreui-free-angular-admin-template -name "main-*.js")
      - sed -i "s|__API_ENDPOINT_URL__|$API_ENDPOINT_URL|" $MAIN_JS_FILE
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/coreui-free-angular-admin-template'
