version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - |
        cat <<EOF > src/environments/environment.prod.ts
        export const environment = {
          production: true,
          apiUrl: '$API_ENDPOINT_URL'
        };
        EOF
      - ng build --configuration production --aot
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/coreui-free-angular-admin-template'
